// Dishes Array contains 7 dishes objects

var dishes = [
  {
    name: "Barbecue Ribs",
    description:
      "These ribs are fall-off-the-bone good and blasted with paprika, brown sugar, chili powder, cumin, oregano, garlic, cayenne pepper, and cracked peppercorns.",
    flagInfo: {
      flagType: "warning",
      flagTypeClass: "warning-dish-info",
      flagIcon: "fa-triangle-exclamation",
      flagTitle: "Extended Preparation Time",
      flagDescription:
        "This recipe requires more than 45 minutes to prepare. Plan accordingly!",
    },
    ratingBadge: { ratingNumber: 4.8, reviewNumber: 555 },
    image: {
      path: "./images/Barbecue_Ribs.jpg", // Search: "Barbecue Ribs"
      imageAlt: "Barbecue Ribs with coleslaw",
    },
    dishTimeServ: { prepTime: 60, cookTime: 30, serveNum: 2 },
    dishDiffTypeBadge: {
      difficaltyType: "hard",
      difficaltyClass: "bg-hard",
      dishType: "Grilled",
      dishTypeClass: "grill-food",
    },
    ingredientList: [
      "2 racks of pork baby back ribs",
      "1/2 cup brown sugar",
      "1/4 cup paprika",
      "1 tablespoon black pepper",
      "1 tablespoon salt",
      "1 tablespoon chili powder",
      "1 tablespoon garlic powder",
      "1 tablespoon onion powder",
      "1 teaspoon cayenne pepper",
      "1 cup barbecue sauce",
      "2 tablespoons apple cider vinegar",
      "1 tablespoon honey",
      "1 tablespoon Worcestershire sauce",
      "1 teaspoon liquid smoke",
      "2 tablespoons olive oil",
      "Butter for finishing",
    ],
    instructionsList: [
      "Remove the membrane from the back of the ribs.",
      "Mix all dry spices together to create the rub.",
      "Rub the spice mix generously over both sides of the ribs.",
      "Wrap the ribs tightly in aluminum foil.",
      "Refrigerate for at least 2 hours (or overnight).",
      "Preheat your oven to 275°F (135°C).",
      "Place wrapped ribs on a baking sheet.",
      "Bake for 2.5 to 3 hours until tender.",
      "Remove ribs from the oven and unwrap carefully.",
      "Mix barbecue sauce, vinegar, and honey in a bowl.",
      "Preheat your grill to medium-high heat.",
      "Brush the ribs generously with the sauce mixture.",
      "Grill ribs for 5-10 minutes per side to caramelize.",
      "Apply more sauce halfway through grilling.",
      "Remove from grill and let rest for 10 minutes.",
      "Slice into individual ribs and serve hot.",
    ],
    chiefList: [
      "Always remove the silver skin membrane for tender ribs.",
      "Marinating overnight allows flavors to penetrate deep.",
      "Low and slow cooking breaks down tough connective tissue.",
      "Wrap in foil to steam the meat and keep it moist.",
      "Don't boil your ribs; it removes the flavor.",
      "Use apple wood chips if smoking for extra flavor.",
      "Apply sauce only at the end to prevent burning the sugar.",
      "Rest the meat to let juices redistribute.",
      "Use a meat thermometer to ensure safety.",
      "Serve with extra sauce on the side.",
      "Coleslaw makes a perfect crunchy side dish.",
    ],
    nutritionTab: {
      caloryUnit: 450,
      proteinUnit: 38,
      carbsUnit: 24,
      fatUnit: 22,
      fiberUnit: 1,
      sodiumUnit: 760,
    },
  },
  {
    name: "Lemon Herb Grilled Salmon",
    description:
      "Fresh Atlantic salmon fillets grilled to perfection with a zesty lemon and herb butter sauce.",
    flagInfo: { flagType: null },
    ratingBadge: { ratingNumber: 4.9, reviewNumber: 890 },
    image: {
      path: "./images/Grilled_Salmon.jpg", // Search: "Grilled Salmon"
      imageAlt: "Grilled Salmon with Lemon",
    },
    dishTimeServ: { prepTime: 10, cookTime: 15, serveNum: 2 },
    dishDiffTypeBadge: {
      difficaltyType: "easy",
      difficaltyClass: "bg-easy",
      dishType: "Seafood",
      dishTypeClass: "sea-food",
    },
    ingredientList: [
      "2 Salmon Fillets (skin on)",
      "2 lemons (sliced and zested)",
      "1/4 cup fresh dill, chopped",
      "4 tablespoons unsalted butter",
      "3 cloves garlic, minced",
      "2 tablespoons olive oil",
      "1 teaspoon sea salt",
      "1/2 teaspoon freshly cracked black pepper",
      "1 tablespoon fresh parsley",
      "1 teaspoon dried thyme",
      "1/2 teaspoon paprika",
      "Asparagus spears (optional side)",
      "Cherry tomatoes (optional side)",
    ],
    instructionsList: [
      "Preheat your grill to medium-high heat.",
      "Clean the grill grates thoroughly.",
      "Rub grill grates with oil to prevent sticking.",
      "Pat the salmon fillets completely dry with paper towels.",
      "Brush salmon with olive oil on both sides.",
      "Season generously with salt, pepper, and paprika.",
      "In a small pan, melt butter with garlic and herbs.",
      "Place salmon on grill, skin side down first.",
      "Cook for 6-8 minutes without moving it to crisp skin.",
      "Flip carefully using a fish spatula.",
      "Cook for another 2-4 minutes until opaque.",
      "Brush with the lemon herb butter mixture.",
      "Remove from grill and let rest for 5 minutes.",
      "Garnish with fresh lemon slices and dill.",
    ],
    chiefList: [
      "Dry the fish well to ensure a good sear.",
      "Don't move the fish until it releases naturally.",
      "Skin-side down protects the meat from drying out.",
      "Use a fish spatula for easier flipping.",
      "Do not overcook; salmon continues cooking while resting.",
      "Fresh herbs provide much better flavor than dried.",
      "Add lemon juice after cooking to keep color bright.",
      "Clarified butter prevents burning at high heat.",
      "Check for pin bones before cooking.",
      "Serve on a warm plate to maintain temperature.",
    ],
    nutritionTab: {
      caloryUnit: 350,
      proteinUnit: 40,
      carbsUnit: 2,
      fatUnit: 18,
      fiberUnit: 0,
      sodiumUnit: 400,
    },
  },
  {
    name: "Classic Beef Burger",
    description:
      "Juicy beef patty topped with cheddar cheese, fresh lettuce, tomato, and our secret house sauce.",
    flagInfo: { flagType: null },
    ratingBadge: { ratingNumber: 4.5, reviewNumber: 1200 },
    image: {
      path: "./images/beef_burger.jpg", // Search: "Classic Cheeseburger"
      imageAlt: "Juicy Beef Burger",
    },
    dishTimeServ: { prepTime: 15, cookTime: 10, serveNum: 1 },
    dishDiffTypeBadge: {
      difficaltyType: "easy",
      difficaltyClass: "bg-easy",
      dishType: "Grilled",
      dishTypeClass: "grill-food",
    },
    ingredientList: [
      "1/2 lb Ground Beef (80/20 blend)",
      "1 Brioche Bun",
      "2 slices Cheddar Cheese",
      "2 leaves Iceberg Lettuce",
      "1 slice Beefsteak Tomato",
      "3 Pickle slices",
      "1/4 Red Onion, sliced rings",
      "1 tablespoon Mayonnaise",
      "1 teaspoon Ketchup",
      "1 teaspoon Yellow Mustard",
      "1/2 teaspoon Garlic Powder",
      "Salt and Pepper to taste",
      "1 tablespoon Butter (for bun)",
    ],
    instructionsList: [
      "Preheat your grill or cast-iron skillet to high heat.",
      "Divide ground beef into loose balls, don't overwork.",
      "Form into patties slightly wider than your buns.",
      "Press a small dimple in the center of each patty.",
      "Season generously with salt and pepper on both sides.",
      "Butter the cut sides of the buns.",
      "Toast buns on the grill until golden brown.",
      "Place patties on the grill and sear for 4 minutes.",
      "Flip patties only once when they release easily.",
      "Add cheese slices during the last minute of cooking.",
      "Cover with a lid to melt the cheese completely.",
      "Mix mayo, ketchup, and mustard for the sauce.",
      "Assemble: Bun, sauce, lettuce, tomato, patty, onion, bun.",
    ],
    chiefList: [
      "Use 80/20 meat-to-fat ratio for juiciness.",
      "Keep the meat cold until the moment it hits the grill.",
      "Never press down on the patty while cooking.",
      "The dimple prevents the burger from puffing up.",
      "Toast the buns to prevent sogginess from juices.",
      "Season right before cooking to keep texture loose.",
      "Let the burger rest for 2 minutes before eating.",
      "Melting cheese helps hold the toppings in place.",
      "Iceberg lettuce provides the best crunch.",
      "Homemade sauce is always better than store-bought.",
    ],
    nutritionTab: {
      caloryUnit: 600,
      proteinUnit: 30,
      carbsUnit: 45,
      fatUnit: 35,
      fiberUnit: 3,
      sodiumUnit: 900,
    },
  },
  {
    name: "Creamy Chicken Alfredo",
    description:
      "Fettuccine pasta tossed in a rich and creamy parmesan cheese sauce with tender grilled chicken.",
    flagInfo: { flagType: null },
    ratingBadge: { ratingNumber: 4.7, reviewNumber: 430 },
    image: {
      path: "./images/chicken_alfredo.jpg", // Search: "Chicken Alfredo"
      imageAlt: "Chicken Alfredo Pasta",
    },
    dishTimeServ: { prepTime: 20, cookTime: 20, serveNum: 4 },
    dishDiffTypeBadge: {
      difficaltyType: "easy",
      difficaltyClass: "bg-easy",
      dishType: "Pasta",
      dishTypeClass: "pasta-food",
    },
    ingredientList: [
      "1 lb Fettuccine Pasta",
      "2 large Chicken Breasts",
      "2 cups Heavy Cream",
      "1.5 cups Parmesan Cheese, grated",
      "1/2 cup Butter",
      "4 cloves Garlic, minced",
      "2 tablespoons Olive Oil",
      "1 teaspoon Salt",
      "1/2 teaspoon White Pepper",
      "1/4 teaspoon Nutmeg",
      "Fresh Parsley for garnish",
      "1/2 cup Pasta Water (reserved)",
      "1 tablespoon Lemon Juice (optional)",
    ],
    instructionsList: [
      "Bring a large pot of salted water to a boil.",
      "Cook fettuccine according to package to al dente.",
      "Reserve 1 cup of starchy pasta water before draining.",
      "Season chicken breasts with salt and pepper.",
      "Heat olive oil in a large skillet over medium-high heat.",
      "Sear chicken until golden and cooked through.",
      "Remove chicken, let rest, then slice into strips.",
      "In the same pan, melt butter and scrape up bits.",
      "Add minced garlic and sauté until fragrant (1 min).",
      "Pour in heavy cream and bring to a gentle simmer.",
      "Reduce heat and stir in parmesan cheese until melted.",
      "Add nutmeg and white pepper to the sauce.",
      "Toss pasta in the sauce, adding pasta water if needed.",
      "Top with sliced chicken and fresh parsley.",
    ],
    chiefList: [
      "Always grate your own parmesan; pre-grated has fillers.",
      "Salt the pasta water heavily (like the ocean).",
      "Don't rinse the pasta; starch helps sauce stick.",
      "Nutmeg adds a subtle, classic depth to cream sauces.",
      "Simmer cream gently; boiling can make it separate.",
      "Garlic burns fast, so watch it closely.",
      "Pasta water is liquid gold for adjusting sauce thickness.",
      "Warm the serving bowls for a better experience.",
      "Serve immediately as cream sauce thickens quickly.",
      "White pepper keeps the sauce looking pristine.",
    ],
    nutritionTab: {
      caloryUnit: 800,
      proteinUnit: 45,
      carbsUnit: 60,
      fatUnit: 40,
      fiberUnit: 2,
      sodiumUnit: 1100,
    },
  },
  {
    name: "Spicy Garlic Shrimp",
    description:
      "Succulent shrimp sautéed in a spicy garlic butter sauce, perfect for a quick and flavorful dinner.",
    flagInfo: { flagType: null },
    ratingBadge: { ratingNumber: 4.6, reviewNumber: 310 },
    image: {
      path: "./images/garlic_shrimp.jpg", // Search: "Spicy Garlic Shrimp"
      imageAlt: "Spicy Garlic Shrimp",
    },
    dishTimeServ: { prepTime: 10, cookTime: 8, serveNum: 2 },
    dishDiffTypeBadge: {
      difficaltyType: "easy",
      difficaltyClass: "bg-easy",
      dishType: "Seafood",
      dishTypeClass: "sea-food",
    },
    ingredientList: [
      "1 lb Large Shrimp (peeled and deveined)",
      "6 cloves Garlic, minced",
      "1 teaspoon Red Chili Flakes",
      "1/4 cup Fresh Parsley, chopped",
      "4 tablespoons Unsalted Butter",
      "2 tablespoons Olive Oil",
      "2 tablespoons Lemon Juice",
      "1/4 cup Dry White Wine",
      "1 teaspoon Paprika",
      "Salt and Black Pepper to taste",
      "Crusty Bread (for serving)",
      "Green Onions for garnish",
    ],
    instructionsList: [
      "Thaw shrimp if frozen and pat them completely dry.",
      "Season shrimp with salt, pepper, and paprika.",
      "Heat olive oil and half the butter in a large skillet.",
      "Add red chili flakes to infuse the oil with heat.",
      "Add shrimp in a single layer; do not overcrowd.",
      "Cook for 1-2 minutes per side until pink.",
      "Remove shrimp from pan and set aside.",
      "Add remaining butter and minced garlic to the pan.",
      "Sauté garlic for 30 seconds until fragrant.",
      "Pour in white wine and lemon juice to deglaze.",
      "Simmer sauce for 2 minutes to reduce slightly.",
      "Return shrimp to pan and toss to coat.",
      "Garnish with parsley and serve with bread.",
    ],
    chiefList: [
      "Patting shrimp dry ensures a sear instead of steaming.",
      "Overcooked shrimp become rubbery; watch closely.",
      " Garlic can turn bitter if burned, cook gently.",
      "Use tails-on shrimp for better presentation.",
      "A dry Pinot Grigio works best for the sauce.",
      "Add cold butter at the end for a glossy sauce.",
      "Serve with crusty bread to soak up the garlic butter.",
      "Adjust chili flakes based on your heat tolerance.",
      "Prep all ingredients before starting (mise en place).",
      "Squeeze fresh lemon right before serving.",
    ],
    nutritionTab: {
      caloryUnit: 250,
      proteinUnit: 22,
      carbsUnit: 3,
      fatUnit: 15,
      fiberUnit: 0,
      sodiumUnit: 650,
    },
  },
  {
    name: "Tomahawk Steak",
    description:
      "A thick, ribeye steak with the bone left long for presentation, grilled to a perfect medium-rare.",
    flagInfo: {
      flagType: "warning",
      flagTypeClass: "warning-dish-info",
      flagIcon: "fa-triangle-exclamation",
      flagTitle: "High Heat Required",
      flagDescription:
        "Requires very high heat grilling and precise timing.",
    },
    ratingBadge: { ratingNumber: 5.0, reviewNumber: 150 },
    image: {
      path: "./images/tomahawk_steak.jpg", // Search: "Tomahawk Steak"
      imageAlt: "Grilled Tomahawk Steak",
    },
    dishTimeServ: { prepTime: 40, cookTime: 25, serveNum: 2 },
    dishDiffTypeBadge: {
      difficaltyType: "hard",
      difficaltyClass: "bg-hard",
      dishType: "Grilled",
      dishTypeClass: "grill-food",
    },
    ingredientList: [
      "1 Tomahawk Steak (approx 2-3 lbs)",
      "2 tablespoons Coarse Sea Salt",
      "1 tablespoon Freshly Cracked Black Pepper",
      "3 sprigs Fresh Rosemary",
      "3 sprigs Fresh Thyme",
      "4 cloves Garlic, smashed",
      "4 tablespoons Unsalted Butter",
      "2 tablespoons Olive Oil",
      "Flaky Salt for finishing",
      "Mashed Potatoes (for side)",
      "Grilled Asparagus (for side)",
    ],
    instructionsList: [
      "Remove steak from fridge 1 hour before cooking.",
      "Pat the steak completely dry with paper towels.",
      "Season liberally with coarse salt and black pepper.",
      "Preheat grill or cast-iron skillet to high heat.",
      "Sear the steak for 3-4 minutes on all sides.",
      "Don't forget to sear the fat cap on the side.",
      "Lower heat or move to indirect heat zone.",
      "Insert a meat thermometer into the thickest part.",
      "Cook until internal temp reaches 130°F (medium-rare).",
      "In the last minutes, add butter, garlic, and herbs.",
      "Baste the steak continuously with the herb butter.",
      "Remove from heat and let rest on a board.",
      "Rest for at least 10-15 minutes before cutting.",
      "Carve the meat off the bone and slice against grain.",
    ],
    chiefList: [
      "Room temperature meat cooks much more evenly.",
      "The bone insulates the meat near it, keeping it rarer.",
      "Use a digital thermometer; guessing is risky.",
      "Resting allows juices to redistribute throughout.",
      "Wrap the bone in foil to prevent it from charring.",
      "Basting adds incredible flavor and moisture.",
      "Slice against the grain for maximum tenderness.",
      "Don't be afraid of salt; it's a thick cut of meat.",
      "Reverse sear method works great for this cut.",
      "Presentation is key; serve on a wooden board.",
    ],
    nutritionTab: {
      caloryUnit: 900,
      proteinUnit: 60,
      carbsUnit: 0,
      fatUnit: 70,
      fiberUnit: 0,
      sodiumUnit: 500,
    },
  },
  {
    name: "Lobster Thermidor",
    description:
      "A classic French dish consisting of a creamy mixture of cooked lobster meat, egg yolks, and brandy.",
    flagInfo: {
      flagType: "attention",
      flagTypeClass: "attention-dish-info",
      flagIcon: "fa-circle-exclamation",
      flagTitle: "Complex Technique",
      flagDescription:
        "Involves creating a delicate roux and handling seafood.",
    },
    ratingBadge: { ratingNumber: 4.9, reviewNumber: 220 },
    image: {
      path: "./images/lobster_thermidor.jpg", // Search: "Lobster Thermidor"
      imageAlt: "Lobster Thermidor",
    },
    dishTimeServ: { prepTime: 45, cookTime: 20, serveNum: 2 },
    dishDiffTypeBadge: {
      difficaltyType: "hard",
      difficaltyClass: "bg-hard",
      dishType: "Seafood",
      dishTypeClass: "sea-food",
    },
    ingredientList: [
      "2 Whole Lobsters (1.5 lbs each)",
      "1/2 cup Gruyère Cheese, grated",
      "1 teaspoon Dijon Mustard",
      "2 tablespoons Brandy or Cognac",
      "2 Egg Yolks",
      "1/2 cup Heavy Cream",
      "4 tablespoons Butter",
      "2 tablespoons Flour",
      "1 cup Whole Milk",
      "2 Shallots, minced",
      "1 tablespoon Fresh Tarragon",
      "1/4 cup Parmesan Cheese",
      "Salt and White Pepper",
      "Lemon wedges for serving",
    ],
    instructionsList: [
      "Steam or boil lobsters for 8 minutes.",
      "Cool lobsters in ice water to stop cooking.",
      "Cut lobsters in half lengthwise and clean cavity.",
      "Remove tail and claw meat, chop into chunks.",
      "Reserve the clean shells for serving.",
      "In a pan, sauté minced shallots in butter.",
      "Add flour and cook for 2 minutes to make a roux.",
      "Whisk in milk and cream slowly until thickened.",
      "Stir in brandy, mustard, tarragon, salt, and pepper.",
      "In a small bowl, temper egg yolks with hot sauce.",
      "Whisk yolk mixture back into the main sauce.",
      "Stir in half the Gruyère cheese until melted.",
      "Fold the chopped lobster meat into the sauce.",
      "Spoon mixture back into the lobster shells.",
      "Top with remaining Gruyère and Parmesan.",
      "Broil for 3-4 minutes until golden and bubbly.",
    ],
    chiefList: [
      "Don't overcook the lobster initially; it cooks again.",
      "Temper egg yolks carefully to avoid scrambling.",
      "High-quality brandy makes a significant difference.",
      "Gruyère adds the authentic nutty flavor profile.",
      "Clean the shells thoroughly for a nice presentation.",
      "White pepper keeps the sauce looking creamy/white.",
      "Serve immediately while the cheese is bubbling.",
      "Watch the broiler closely; cheese burns fast.",
      "Tarragon is the traditional herb, don't skip it.",
      "Serve with a simple green salad to cut the richness.",
    ],
    nutritionTab: {
      caloryUnit: 550,
      proteinUnit: 35,
      carbsUnit: 10,
      fatUnit: 40,
      fiberUnit: 1,
      sodiumUnit: 850,
    },
  },
  {
    name: "Caesar Salad",
    description:
      "Crisp romaine lettuce tossed with croutons, parmesan cheese, and a tangy homemade Caesar dressing.",
    flagInfo: { flagType: null },
    ratingBadge: { ratingNumber: 4.3, reviewNumber: 670 },
    image: {
      path: "./images/caesar_salad.jpg", // Search: "Caesar Salad"
      imageAlt: "Fresh Caesar Salad",
    },
    dishTimeServ: { prepTime: 20, cookTime: 0, serveNum: 2 },
    dishDiffTypeBadge: {
      difficaltyType: "easy",
      difficaltyClass: "bg-easy",
      dishType: "Salad",
      dishTypeClass: "salad-food",
    },
    ingredientList: [
      "2 heads Romaine Lettuce",
      "1 cup Homemade Croutons",
      "1/2 cup Parmesan Cheese, shaved",
      "2 tsp Anchovy Paste (or fillets)",
      "1 large Egg Yolk",
      "1 tablespoon Lemon Juice",
      "1 teaspoon Dijon Mustard",
      "1 teaspoon Worcestershire Sauce",
      "1/2 cup Extra Virgin Olive Oil",
      "2 cloves Garlic, minced",
      "Freshly Cracked Black Pepper",
      "Pinch of Salt",
    ],
    instructionsList: [
      "Wash lettuce thoroughly and dry completely.",
      "Tear lettuce leaves into bite-sized pieces.",
      "In a bowl, whisk egg yolk, lemon juice, and mustard.",
      "Add anchovy paste, garlic, and Worcestershire.",
      "Slowly drizzle in olive oil while whisking vigorously.",
      "Whisk until the dressing emulsifies and thickens.",
      "Stir in half of the grated parmesan cheese.",
      "Add plenty of black pepper to the dressing.",
      "Place lettuce in a large bowl.",
      "Pour dressing over lettuce and toss to coat evenly.",
      "Add croutons and toss again gently.",
      "Top with remaining shaved parmesan cheese.",
      "Serve immediately on chilled plates.",
    ],
    chiefList: [
      "Lettuce must be completely dry or dressing won't stick.",
      "Use room temperature ingredients for the emulsion.",
      "Anchovies provide the signature savory 'umami' flavor.",
      "Add the oil drop-by-drop initially to prevent breaking.",
      "Homemade croutons are vastly superior to store-bought.",
      "Use a wooden bowl for tossing if you have one.",
      "Chill your serving plates for a crisp salad.",
      "Don't over-dress; the leaves shouldn't be swimming.",
      "Fresh lemon juice is non-negotiable.",
      "Toss gently to avoid bruising the lettuce leaves.",
    ],
    nutritionTab: {
      caloryUnit: 300,
      proteinUnit: 8,
      carbsUnit: 15,
      fatUnit: 25,
      fiberUnit: 4,
      sodiumUnit: 500,
    },
  },
  {
    name: "Lamb Chops",
    description:
      "Tender lamb chops marinated in garlic and herbs, pan-seared to develop a beautiful crust.",
    flagInfo: { flagType: null },
    ratingBadge: { ratingNumber: 4.8, reviewNumber: 405 },
    image: {
      path: "./images/lamb_chops.jpg", // Search: "Lamb Chops"
      imageAlt: "Grilled Lamb Chops",
    },
    dishTimeServ: { prepTime: 30, cookTime: 15, serveNum: 3 },
    dishDiffTypeBadge: {
      difficaltyType: "hard",
      difficaltyClass: "bg-hard",
      dishType: "Grilled",
      dishTypeClass: "grill-food",
    },
    ingredientList: [
      "8 Lamb Rib Chops",
      "4 cloves Garlic, minced",
      "2 tablespoons Fresh Thyme",
      "2 tablespoons Fresh Rosemary",
      "3 tablespoons Olive Oil",
      "1 teaspoon Sea Salt",
      "1 teaspoon Black Pepper",
      "2 tablespoons Butter",
      "1 tablespoon Lemon Juice",
      "Fresh Mint (for garnish/sauce)",
      "1/2 cup Greek Yogurt (optional sauce)",
      "1/4 cup Cucumber, grated (optional sauce)",
      "1 teaspoon Dried Oregano",
    ],
    instructionsList: [
      "Take lamb chops out of fridge 20 mins before cooking.",
      "Finely mince the garlic, rosemary, and thyme.",
      "In a small bowl, mix herbs, garlic, and olive oil.",
      "Rub the marinade all over the lamb chops.",
      "Let marinate at room temp for 30 minutes.",
      "Heat a cast-iron skillet over medium-high heat.",
      "Place chops in skillet, do not crowd the pan.",
      "Sear for 3-4 minutes until a brown crust forms.",
      "Flip and cook for 3 minutes on the other side.",
      "Add butter to the pan and baste the chops.",
      "Sear the fat strip on the edge for 1 minute.",
      "Check internal temp (125°F for medium-rare).",
      "Remove from pan and rest for 5-10 minutes.",
      "Squeeze fresh lemon juice over chops before serving.",
    ],
    chiefList: [
      "Don't crowd the pan or the meat will steam.",
      "Getting a good crust (Maillard reaction) is flavor.",
      "Lamb is best served medium-rare to medium.",
      "Render the fat cap on the edge so it's crispy.",
      "Fresh herbs make a huge difference with lamb.",
      "Resting allows the juices to settle back in.",
      "Mint jelly or mint sauce is a classic pairing.",
      "Lemon juice cuts through the richness of the fat.",
      "Cast iron retains heat best for searing.",
      "Buy 'frenched' chops for a cleaner presentation.",
    ],
    nutritionTab: {
      caloryUnit: 400,
      proteinUnit: 30,
      carbsUnit: 0,
      fatUnit: 28,
      fiberUnit: 0,
      sodiumUnit: 300,
    },
  },
  {
    name: "Spaghetti Bolognese",
    description:
      "A rich and savory meat sauce simmered with tomatoes, onions, and herbs, served over al dente spaghetti.",
    flagInfo: {
      flagType: "warning",
      flagTypeClass: "warning-dish-info",
      flagIcon: "fa-clock",
      flagTitle: "Slow Cook",
      flagDescription:
        "The sauce tastes best when simmered for at least 2 hours.",
    },
    ratingBadge: { ratingNumber: 4.6, reviewNumber: 950 },
    image: {
      path: "./images/spaghetti_bolognese.jpg", // Search: "Spaghetti Bolognese"
      imageAlt: "Spaghetti Bolognese",
    },
    dishTimeServ: { prepTime: 20, cookTime: 120, serveNum: 6 },
    dishDiffTypeBadge: {
      difficaltyType: "easy",
      difficaltyClass: "bg-easy",
      dishType: "Pasta",
      dishTypeClass: "pasta-food",
    },
    ingredientList: [
      "1 lb Ground Beef",
      "1/2 lb Ground Pork (optional)",
      "4 slices Bacon or Pancetta, diced",
      "1 large Onion, finely diced",
      "1 Carrot, finely diced",
      "1 Celery stalk, finely diced",
      "4 cloves Garlic, minced",
      "2 tablespoons Tomato Paste",
      "28 oz Crushed Tomatoes (canned)",
      "1/2 cup Dry Red Wine",
      "1 cup Beef Broth",
      "1/2 cup Whole Milk",
      "1 lb Spaghetti Pasta",
      "Pinch of Nutmeg",
      "Fresh Basil and Oregano",
      "Parmesan Cheese for serving",
    ],
    instructionsList: [
      "Heat olive oil in a large pot or dutch oven.",
      "Sauté bacon/pancetta until crispy.",
      "Add ground meats and brown well, breaking up lumps.",
      "Remove meat and set aside, leaving fat in pan.",
      "Add onion, carrot, celery (soffritto) to the pan.",
      "Cook veggies until softened and onions are translucent.",
      "Stir in garlic and tomato paste, cook for 1 minute.",
      "Pour in red wine to deglaze, scraping the bottom.",
      "Return meat to the pan.",
      "Add crushed tomatoes and beef broth.",
      "Bring to a boil, then reduce heat to very low.",
      "Simmer covered for at least 1.5 - 2 hours.",
      "Stir in milk and nutmeg in the last 20 minutes.",
      "Cook spaghetti in salted water until al dente.",
      "Toss pasta directly with the sauce before serving.",
    ],
    chiefList: [
      "The 'holy trinity' (onion, carrot, celery) is essential.",
      "Milk tenderizes the meat; don't skip it.",
      "Long simmering develops deep, complex flavors.",
      "Pasta water helps the sauce cling to the noodles.",
      "Finish cooking the pasta in the sauce itself.",
      "Using a mix of beef and pork adds flavor depth.",
      "San Marzano tomatoes are the best for sauce.",
      "A parmesan rind in the simmering sauce adds umami.",
      "Deglazing with wine picks up all the flavor bits.",
      "Serve with a heavy dusting of parmesan cheese.",
    ],
    nutritionTab: {
      caloryUnit: 550,
      proteinUnit: 25,
      carbsUnit: 65,
      fatUnit: 20,
      fiberUnit: 5,
      sodiumUnit: 800,
    },
  },
  {
    name: "Tuna Tartare",
    description:
      "Fresh raw tuna cubes seasoned with soy sauce, sesame oil, and avocado for a refreshing appetizer.",
    flagInfo: {
      flagType: "attention",
      flagTypeClass: "attention-dish-info",
      flagIcon: "fa-circle-exclamation",
      flagTitle: "Raw Ingredients",
      flagDescription: "Ensure you use sushi-grade tuna for safety.",
    },
    ratingBadge: { ratingNumber: 4.8, reviewNumber: 180 },
    image: {
      path: "./images/tuna_tartare.jpg", // Search: "Tuna Tartare"
      imageAlt: "Tuna Tartare",
    },
    dishTimeServ: { prepTime: 20, cookTime: 0, serveNum: 2 },
    dishDiffTypeBadge: {
      difficaltyType: "hard",
      difficaltyClass: "bg-hard",
      dishType: "Seafood",
      dishTypeClass: "sea-food",
    },
    ingredientList: [
      "1 lb Sushi-Grade Ahi Tuna",
      "2 Ripe Avocados",
      "3 tablespoons Soy Sauce",
      "1 tablespoon Sesame Oil",
      "1 teaspoon Toasted Sesame Seeds",
      "1 teaspoon Fresh Ginger, grated",
      "1 tablespoon Lime Juice",
      "2 Green Onions, thinly sliced",
      "1 teaspoon Sriracha (optional)",
      "1/2 Cucumber, finely diced",
      "Fresh Cilantro leaves",
      "Wonton Chips or Crackers (for serving)",
      "Wasabi paste (optional side)",
    ],
    instructionsList: [
      "Place tuna in freezer for 15 mins (easier to cut).",
      "Dice the tuna into small, uniform 1/4 inch cubes.",
      "Dice the avocado into similar sized cubes.",
      "Toss avocado with lime juice to prevent browning.",
      "In a bowl, whisk soy sauce, sesame oil, ginger, sriracha.",
      "Add the diced tuna to the sauce and toss gently.",
      "Fold in the green onions and cucumber.",
      "Place a ring mold on a serving plate.",
      "Add a layer of avocado at the bottom of the mold.",
      "Top with the tuna mixture, pressing down gently.",
      "Carefully remove the ring mold.",
      "Sprinkle with sesame seeds and cilantro.",
      "Serve immediately with wonton chips.",
    ],
    chiefList: [
      "Temperature is safety: keep the fish very cold.",
      "Use a very sharp knife to avoid mashing the fish.",
      "Uniform dicing improves texture and presentation.",
      "Mix gently; you want distinct cubes, not mush.",
      "Acid cooks fish (ceviche), so add lime last minute.",
      "Serve immediately; this dish does not keep well.",
      "Hygiene is paramount when working with raw food.",
      "The avocado adds necessary creaminess to the dish.",
      "Toast sesame seeds for extra nuttiness.",
      "Layering creates a professional restaurant look.",
    ],
    nutritionTab: {
      caloryUnit: 220,
      proteinUnit: 20,
      carbsUnit: 8,
      fatUnit: 12,
      fiberUnit: 3,
      sodiumUnit: 450,
    },
  },
];